---
- name: 2nd day challenge
  hosts: renamed,!taz
  gather_facts: False
  connection: ssh
  
  vars_prompt:
        - name: uusername
          prompt: "please enter the new username"
          private: no

        - name: ppassword
          prompt: "Please enter the password"
          private: yes
          confirm: yes     

  tasks:
  # create a new group
  - name: Create group 'funkytown'
    group:
            name: funkytown
            state: present
    become: yes

  # create new user on target system
  - name: "Add user with group of 'funkytown'"
    user:
              name: "{{ uusername }}"
              comment: Add user "{{ uusername }}" with group of 'funkytown'
              password: "{{ ppassword }}"
              state: present
              shell: /bin/bash       # Defaults to /bin/bash
              system: no             # Defaults to no
              createhome: yes        # Defaults to yes
              #home: /home/exampleuser  # Defaults to /home/<username>
              #group: funkytown
    become: yes
