---
- name: copy from controller to hosts
  hosts: planetexpress,!farnsworth
  gather_facts: yes

  tasks:
          - name: copy gather fact var data into hosts
            copy:
                    content: "{{ ansible_all_ipv4_addresses }}"  # facts gathered from host
                    dest: ~/ipv4info.txt                         # homedir on hosts
                    backup: yes                                  # make backup of original
                    force: yes                                   # file always copied when content is diff

